/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gerente.java
 *
 * Created on 19/03/2013, 15:31:42
 */
package Visão;

import Controle.ControleCliente;
import Controle.ControleDeFuncionario;
import Controle.ControleHistoricoDeVendas;
import Controle.ControleProduto;
import Sistema.Gerente;
import java.awt.image.ImageObserver;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 11031065
 */
public class GerenteView extends javax.swing.JFrame {
    
    Gerente gerente;
    Login login;
    
    /** Creates new form Gerente */
    public GerenteView(Gerente gerente, Login login) {
        initComponents();
        alterarProdutoPanel.setVisible(false);
        this.login = login;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inserirClienteButton = new javax.swing.JButton();
        campoCpfCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        localizarClienteButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        listarButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoCodigoProduto = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        listarEstoqueButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        campoEstoqueCodigoProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        alterarProdutoPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        campoNomeProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoQtdEstoque = new javax.swing.JTextField();
        atualizarProdutoButton = new javax.swing.JButton();
        cancelarAlteracaoButton = new javax.swing.JButton();
        IncluirButton = new javax.swing.JButton();
        alterarProdutoButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        listarFuncionariosButton = new javax.swing.JButton();
        campoMatriculaFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buscarFuncionarioButton = new javax.swing.JButton();
        excluirFuncionarioButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente Preferencial"));

        inserirClienteButton.setText("Inserir Cliente");
        inserirClienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserirClienteButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Localizar pelo Cpf:");

        localizarClienteButton.setText("Localizar");
        localizarClienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localizarClienteButtonMouseClicked(evt);
            }
        });
        localizarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizarClienteButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirButtonMouseClicked(evt);
            }
        });
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Listar Todos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(localizarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserirClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localizarClienteButton)
                    .addComponent(inserirClienteButton)
                    .addComponent(excluirButton)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas"));

        listarButton.setText("Listar Histórico");
        listarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarButtonMouseClicked(evt);
            }
        });
        listarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar Venda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Produto"));

        jLabel7.setText("Código do Produto:");

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque"));

        jLabel9.setText("Listar Produtos");

        listarEstoqueButton.setText("Listar");
        listarEstoqueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarEstoqueButtonMouseClicked(evt);
            }
        });

        jLabel10.setText("Alterar e Incluir Produto");

        jLabel11.setText("CódigoProduto:");

        alterarProdutoPanel.setBackground(new java.awt.Color(153, 255, 153));

        jLabel12.setText("Nome:");

        campoNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeProdutoActionPerformed(evt);
            }
        });

        jLabel13.setText("Fornecedor:");

        jLabel14.setText("Preço:");

        jLabel15.setText("Quantidade em Estoque:");

        atualizarProdutoButton.setText("Atualizar");
        atualizarProdutoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizarProdutoButtonMouseClicked(evt);
            }
        });
        atualizarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarProdutoButtonActionPerformed(evt);
            }
        });

        cancelarAlteracaoButton.setText("Cancelar");
        cancelarAlteracaoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarAlteracaoButtonMouseClicked(evt);
            }
        });

        IncluirButton.setText("Incluir");
        IncluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alterarProdutoPanelLayout = new javax.swing.GroupLayout(alterarProdutoPanel);
        alterarProdutoPanel.setLayout(alterarProdutoPanelLayout);
        alterarProdutoPanelLayout.setHorizontalGroup(
            alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarProdutoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(alterarProdutoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQtdEstoque))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarProdutoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarProdutoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(alterarProdutoPanelLayout.createSequentialGroup()
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alterarProdutoPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alterarProdutoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cancelarAlteracaoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(IncluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarProdutoButton))
        );
        alterarProdutoPanelLayout.setVerticalGroup(
            alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterarProdutoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(alterarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarProdutoButton)
                    .addComponent(IncluirButton)
                    .addComponent(cancelarAlteracaoButton)))
        );

        alterarProdutoButton.setText("Alterar");
        alterarProdutoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarProdutoButtonMouseClicked(evt);
            }
        });
        alterarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarProdutoButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Incluir Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Excluir Produto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEstoqueCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                    .addComponent(alterarProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(36, 36, 36)
                                .addComponent(listarEstoqueButton))
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(alterarProdutoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarEstoqueButton)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEstoqueCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarProdutoButton)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento De Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        jButton5.setText("Incluir Funcionário");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        listarFuncionariosButton.setText("Listar Funcionários");
        listarFuncionariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFuncionariosButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Matrícula:");

        buscarFuncionarioButton.setText("Buscar");
        buscarFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFuncionarioButtonActionPerformed(evt);
            }
        });

        excluirFuncionarioButton.setText("Excluir");
        excluirFuncionarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFuncionarioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarFuncionariosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMatriculaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(buscarFuncionarioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirFuncionarioButton)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(campoMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarFuncionariosButton)
                    .addComponent(buscarFuncionarioButton)
                    .addComponent(excluirFuncionarioButton)))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEditingColumn(0);
        jTable1.setEditingRow(0);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Cliente Preferêncial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirClienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserirClienteButtonMouseClicked
        CadastroCliente cliente = new CadastroCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_inserirClienteButtonMouseClicked

    private void localizarClienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localizarClienteButtonMouseClicked
        String cpf = campoCpfCliente.getText();
        if(cpf.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o cpf", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            if(!ControleCliente.contemCpf(cpf)){
                JOptionPane.showMessageDialog(this, "Cliente não cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else{
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setColumnCount(7);
                String colunas[] = {"Cpf", "Nome", "Identidade","Endereco","Data de Cadastro"," Bonus", "Email"};
                model.setColumnIdentifiers(colunas);
                model.setNumRows(0);
                Object tupla []= ControleCliente.buscaTupla(cpf);
                
                model.addRow(tupla);
            }
        }
        
    }//GEN-LAST:event_localizarClienteButtonMouseClicked

    private void campoNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeProdutoActionPerformed

    private void atualizarProdutoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarProdutoButtonMouseClicked
        String codigo = campoEstoqueCodigoProduto.getText();
        String nome = campoNomeProduto.getText();
        String descricao = campoDescricao.getText();
        String preco = campoPreco.getText();
        String quantidade = campoQtdEstoque.getText();
        if(nome.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o nome do produto", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(descricao.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira a descricao do produto", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(preco.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o preço do produto", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(quantidade.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira a quantidade do produto", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ControleProduto.atualizaProduto(codigo, nome, descricao, preco, quantidade);
        // chama a função de atualização;
        campoNomeProduto.setText("");
        campoDescricao.setText("");
        campoPreco.setText("");
        campoQtdEstoque.setText("");
        alterarProdutoPanel.setVisible(false);
        campoEstoqueCodigoProduto.setText("");
    }//GEN-LAST:event_atualizarProdutoButtonMouseClicked

    private void alterarProdutoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarProdutoButtonMouseClicked
        String codigo = campoEstoqueCodigoProduto.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira um código", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ControleProduto.pertence(codigo)){
            IncluirButton.setVisible(false);
            alterarProdutoButton.setVisible(true);
            alterarProdutoPanel.setVisible(true);
            campoNomeProduto.setText(ControleProduto.getNomeProduto(codigo));
            campoDescricao.setText(ControleProduto.getFornecedor(codigo));
            campoPreco.setText(ControleProduto.getPreco(codigo));
            campoQtdEstoque.setText(ControleProduto.getQuantidade(codigo));
        }
        else{
            JOptionPane.showMessageDialog(this, "Código de produto não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_alterarProdutoButtonMouseClicked

    private void cancelarAlteracaoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarAlteracaoButtonMouseClicked
        campoNomeProduto.setText("");
        campoDescricao.setText("");
        campoPreco.setText("");
        campoQtdEstoque.setText("");
        alterarProdutoPanel.setVisible(false);
        campoEstoqueCodigoProduto.setText("");
    }//GEN-LAST:event_cancelarAlteracaoButtonMouseClicked

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        if(!ControleCliente.removeCliente(campoCpfCliente.getText()))
          JOptionPane.showMessageDialog(this, "Por favor insira um cpf válido", "ERRO", JOptionPane.ERROR_MESSAGE);  
        
        else {
            campoCpfCliente.setText("");
        }
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void listarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarButtonMouseClicked

    }//GEN-LAST:event_listarButtonMouseClicked

    private void excluirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirButtonMouseClicked

    private void listarEstoqueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarEstoqueButtonMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(5);
        String colunas[] = {"Codigo", "Nome", "Fornecedor","Preço","Estoque"};
        model.setColumnIdentifiers(colunas);
        model.setNumRows(0);
        Object info[][] = ControleProduto.buscaInfo();
        for (int i = 0; i < info.length; i++) {
            model.addRow(info[i]);            
        }
        
    }//GEN-LAST:event_listarEstoqueButtonMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String codigo = campoEstoqueCodigoProduto.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira um código", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ControleProduto.pertence(codigo)){
            JOptionPane.showMessageDialog(this, "Código de produto já incluido no sistema", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            IncluirButton.setVisible(true);
            atualizarProdutoButton.setVisible(false);
            alterarProdutoPanel.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void atualizarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarProdutoButtonActionPerformed

    private void IncluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirButtonActionPerformed
        String codigoDeProduto = campoEstoqueCodigoProduto.getText();
        String nome = campoNomeProduto.getText();
        String fornecedor = campoDescricao.getText();
         double valor;
         
        if(codigoDeProduto.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o codigo do produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else if(nome.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o nome do produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else if(fornecedor.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o nome do fornecedor", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else if(campoPreco.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o preço do produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            valor = Double.parseDouble(campoPreco.getText());
        
            if(campoQtdEstoque.getText().isEmpty())
                JOptionPane.showMessageDialog(this, "Por favor insira a quantidade em estoque", "Erro", JOptionPane.ERROR_MESSAGE);
            else{
                int quantidadeEstoque = Integer.parseInt(campoQtdEstoque.getText());
                if(!ControleProduto.insereProduto(codigoDeProduto, nome, fornecedor, valor, quantidadeEstoque))
                    JOptionPane.showMessageDialog(this, "Código de produto já cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        campoEstoqueCodigoProduto.setText("");
        campoNomeProduto.setText("");
        campoDescricao.setText("");
        campoQtdEstoque.setText("");
        campoPreco.setText("");
        alterarProdutoPanel.setVisible(false);
    }//GEN-LAST:event_IncluirButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        IncluirFuncionarioView cadastro= new IncluirFuncionarioView();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void alterarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alterarProdutoButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String codigo = campoEstoqueCodigoProduto.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o código do produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(!ControleProduto.removeProduto(codigo))
                JOptionPane.showMessageDialog(this, "Produto não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        campoEstoqueCodigoProduto.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void listarFuncionariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionariosButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(5);
        String colunas[] = {"Matricula", "Nome", "Cpf","Identidade","Perfil"};
        model.setColumnIdentifiers(colunas);
        model.setNumRows(0);
       Object info[][] = ControleDeFuncionario.buscaInfo();
        for (int i = 0; i < info.length; i++) {
            model.addRow(info[i]);         
        }
    }//GEN-LAST:event_listarFuncionariosButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setColumnCount(7);
        String colunas[] = {"Cpf", "Nome", "Identidade","Endereco","Data de Cadastro"," Bonus", "Email"};
        model.setColumnIdentifiers(colunas);
        model.setNumRows(0);
       Object info[][] = ControleCliente.buscaInfo();
        for (int i = 0; i < info.length; i++) {
            model.addRow(info[i]);         
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void buscarFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFuncionarioButtonActionPerformed
        String matricula = campoMatriculaFuncionario.getText();
        
        if(matricula.isEmpty())
            JOptionPane.showMessageDialog(this, "Pos favor insira a matrícula do funcionário", "Erro", JOptionPane.ERROR_MESSAGE);
        else{
            if(!ControleDeFuncionario.contemMatricula(matricula))
                JOptionPane.showMessageDialog(this, "Matrícula inexistente", "Erro", JOptionPane.ERROR_MESSAGE);
            else{
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setColumnCount(5);
                String colunas[] = {"Matricula", "Nome", "Cpf","Identidade","Perfil"};
                model.setColumnIdentifiers(colunas);
                Object tupla[] = ControleDeFuncionario.buscaFuncionario(matricula);
                model.setNumRows(0);
                model.addRow(tupla);
            }
            campoMatriculaFuncionario.setText("");
        }
        
        
    }//GEN-LAST:event_buscarFuncionarioButtonActionPerformed

    private void excluirFuncionarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFuncionarioButtonActionPerformed
        String matricula = campoMatriculaFuncionario.getText();
        if(matricula.isEmpty())
            JOptionPane.showMessageDialog(this, "Pos favor insira o número de matrula", "Erro", JOptionPane.ERROR_MESSAGE);
        else{
            if(!ControleDeFuncionario.contemMatricula(matricula))
                JOptionPane.showMessageDialog(this, "Matrícula inexistente", "Erro", JOptionPane.ERROR_MESSAGE);
            else{
                ControleDeFuncionario.removeFuncionario(matricula);
            }
            campoMatriculaFuncionario.setText("");
        }
    }//GEN-LAST:event_excluirFuncionarioButtonActionPerformed

    private void localizarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizarClienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localizarClienteButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String codigo = campoCodigoProduto.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor insira o código do produto", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ControleProduto.pertence(codigo)){
            JOptionPane.showMessageDialog(this, "Produto não localizado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnCount(5);
            String colunas[] = {"Codigo", "Nome", "Fornecedor","Preço","Estoque"};
            model.setColumnIdentifiers(colunas);
            model.setNumRows(0);
            Object tupla[] = ControleProduto.buscaProduto(codigo);
            model.addRow(tupla);
        }       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void listarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarButtonActionPerformed
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnCount(3);
            String colunas[] = {"Nf", "Nome do vendedor", "Valor da compra"};
            model.setColumnIdentifiers(colunas);
            model.setNumRows(0);
            
            Object tuplas [][] = ControleHistoricoDeVendas.getVizualizacao();
            for(int i = 0; i < tuplas.length; i++)
                model.addRow(tuplas[i]);
    }//GEN-LAST:event_listarButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valor = JOptionPane.showInputDialog(this, "Por favor entre com o número do cupom");
        if(valor.isEmpty())
            return;
        int n = Integer.parseInt(valor);
        ControleHistoricoDeVendas.removeVenda(n);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IncluirButton;
    private javax.swing.JButton alterarProdutoButton;
    private javax.swing.JPanel alterarProdutoPanel;
    private javax.swing.JButton atualizarProdutoButton;
    private javax.swing.JButton buscarFuncionarioButton;
    private javax.swing.JTextField campoCodigoProduto;
    private javax.swing.JTextField campoCpfCliente;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoEstoqueCodigoProduto;
    private javax.swing.JTextField campoMatriculaFuncionario;
    private javax.swing.JTextField campoNomeProduto;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JTextField campoQtdEstoque;
    private javax.swing.JButton cancelarAlteracaoButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JButton excluirFuncionarioButton;
    private javax.swing.JButton inserirClienteButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listarButton;
    private javax.swing.JButton listarEstoqueButton;
    private javax.swing.JButton listarFuncionariosButton;
    private javax.swing.JButton localizarClienteButton;
    // End of variables declaration//GEN-END:variables
}
