/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.ControleCliente;
import Controle.ControleDados;
import Controle.ControlePedido;
import Sistema.Cliente;
import Sistema.Pagamento;
import Sistema.PagamentoEmCredito;
import Sistema.PagamentoEmDebito;
import Sistema.PagamentoEmDinheiro;
import Sistema.Vendedor;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class VendedorView extends javax.swing.JFrame {

    /**
     * Creates new form Vendedor
     */
    String tela;
    String visor2;
    double valor;
    ControlePedido controlePedido;
    Vendedor vendedor;
    Cliente cliente;
    Login login;
    DefaultTableModel model;     

    public VendedorView(Vendedor vendedor, Login login) {
        initComponents();
        valor = 0.00;
        tela = "#########################################################################################\n";
        //jTextArea1.setEditable(false);
        //jTextArea1.setText(tela);
        creditoPanel.setVisible(false);
        cartaoDeDebitoPanel.setVisible(false);
        dinheiroPanel.setVisible(false);
        controlePedido = new ControlePedido(vendedor);
        this.vendedor = vendedor;
        this.login = login;
        model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
    }

    private void geraNovoPedido(){
        campoCodigo.setText("");
        campoValor.setText("");
        controlePedido = new ControlePedido(vendedor);
//        jTextArea1.setText(tela);
        totalLabel.setText("0.00");
        if(dinheiroPanel.isVisible()){
            dinheiroPanel.setVisible(false);
            campoTroco.setText("");
        }
        campoCpf.setText("");
        model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        incluirButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        localizarClienteButton = new javax.swing.JButton();
        CadastrarClienteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        pagamentosBox = new javax.swing.JComboBox();
        campoValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        efetuarPagamentoButton = new javax.swing.JButton();
        cartaoDeDebitoPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        campoCartaoDeDebito = new javax.swing.JTextField();
        cartaoDeDebitoButton = new javax.swing.JButton();
        creditoPanel = new javax.swing.JPanel();
        campoCartaoDeCredito = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoCodigoDeSeguranca = new javax.swing.JTextField();
        cartaoDeCreditoButton = new javax.swing.JButton();
        dinheiroPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        campoTroco = new javax.swing.JTextField();
        okDinheiroButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setTitle("Vendedor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Do Produto", "Nome", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inserir Item");

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo:");

        incluirButton.setText("Incluir");
        incluirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incluirButtonMouseClicked(evt);
            }
        });
        incluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Cliente Preferêncial");

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });

        jLabel4.setText("Cpf:");

        localizarClienteButton.setText("Localizar");
        localizarClienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                localizarClienteButtonMouseClicked(evt);
            }
        });

        CadastrarClienteButton.setText("Cadastrar");
        CadastrarClienteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CadastrarClienteButtonMousePressed(evt);
            }
        });

        jLabel5.setText("Quantidade:");

        pagamentosBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão De Crédito", "Cartão de Débito" }));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Efetuar Pagamento");

        jLabel7.setText("Valor:");

        efetuarPagamentoButton.setText("Efetuar Pagamento");
        efetuarPagamentoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                efetuarPagamentoButtonMouseClicked(evt);
            }
        });

        cartaoDeDebitoPanel.setBackground(new java.awt.Color(255, 204, 204));
        cartaoDeDebitoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Número do Cartão: ");

        cartaoDeDebitoButton.setText("Ok");
        cartaoDeDebitoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoDeDebitoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cartaoDeDebitoPanelLayout = new javax.swing.GroupLayout(cartaoDeDebitoPanel);
        cartaoDeDebitoPanel.setLayout(cartaoDeDebitoPanelLayout);
        cartaoDeDebitoPanelLayout.setHorizontalGroup(
            cartaoDeDebitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaoDeDebitoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cartaoDeDebitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartaoDeDebitoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaoDeDebitoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCartaoDeDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        cartaoDeDebitoPanelLayout.setVerticalGroup(
            cartaoDeDebitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaoDeDebitoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cartaoDeDebitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoCartaoDeDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaoDeDebitoButton)
                .addGap(5, 5, 5))
        );

        creditoPanel.setBackground(new java.awt.Color(255, 204, 204));
        creditoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        campoCartaoDeCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCartaoDeCreditoActionPerformed(evt);
            }
        });

        jLabel8.setText("Número do Cartão de Credito:");

        jLabel9.setText("Código de Segurança:");

        cartaoDeCreditoButton.setText("Ok");
        cartaoDeCreditoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoDeCreditoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout creditoPanelLayout = new javax.swing.GroupLayout(creditoPanel);
        creditoPanel.setLayout(creditoPanelLayout);
        creditoPanelLayout.setHorizontalGroup(
            creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCartaoDeCredito))
                    .addGroup(creditoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigoDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cartaoDeCreditoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        creditoPanelLayout.setVerticalGroup(
            creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoCartaoDeCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(creditoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCodigoDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cartaoDeCreditoButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        dinheiroPanel.setBackground(new java.awt.Color(255, 204, 204));
        dinheiroPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Troco:");

        campoTroco.setEditable(false);

        okDinheiroButton.setText("Ok");
        okDinheiroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okDinheiroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dinheiroPanelLayout = new javax.swing.GroupLayout(dinheiroPanel);
        dinheiroPanel.setLayout(dinheiroPanelLayout);
        dinheiroPanelLayout.setHorizontalGroup(
            dinheiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dinheiroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okDinheiroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        dinheiroPanelLayout.setVerticalGroup(
            dinheiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dinheiroPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(dinheiroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okDinheiroButton))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(efetuarPagamentoButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(pagamentosBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incluirButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(109, 109, 109))
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localizarClienteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CadastrarClienteButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addComponent(creditoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dinheiroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartaoDeDebitoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(incluirButton)
                    .addComponent(jLabel5)
                    .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(localizarClienteButton)
                    .addComponent(CadastrarClienteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagamentosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(efetuarPagamentoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dinheiroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaoDeDebitoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Subtotal");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("R$");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalLabel.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel12)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCpfActionPerformed

    //Cadastrar Cliente
    private void CadastrarClienteButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarClienteButtonMousePressed
        CadastroCliente novo = new CadastroCliente();
        novo.setVisible(true);
    }//GEN-LAST:event_CadastrarClienteButtonMousePressed
    //função q deve localizar o cadastro do cliente
    private void localizarClienteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localizarClienteButtonMouseClicked
        String cpf = campoCpf.getText();
        if (cpf.isEmpty()) 
            JOptionPane.showMessageDialog(this, "Por favor insira o Cpf", "Erro", JOptionPane.ERROR_MESSAGE);
        
        else{
            double bonus = ControleCliente.buscaCliente(cpf);
            if(bonus == -1)
                JOptionPane.showMessageDialog(this, "Cliente não cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            else{
                int resp = JOptionPane.showConfirmDialog(this, "Deseja usar o bônus existente?");
                if(resp == 0){
                    double valor = controlePedido.getValorTotal();
                    if(bonus > valor){
                        ControleCliente.atualizarBonus(cpf, bonus - valor);
                        controlePedido.setBonus(valor);
                    }
                    else{
                        controlePedido.setBonus(valor);
                        ControleCliente.atualizarBonus(cpf, 0);
                        double total = controlePedido.getValorTotal() - bonus;
                        totalLabel.setText(""+total);
                        campoCpf.setText("");
                    }
                }
            }
        }
        
    }//GEN-LAST:event_localizarClienteButtonMouseClicked

    private void incluirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incluirButtonMouseClicked
        if (campoCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor insira o codigo", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            String codigo = campoCodigo.getText();
            int quantidade;
            if (campoQuantidade.getText().isEmpty()) {
                quantidade = 1;
            } else {
                quantidade = Integer.parseInt(campoQuantidade.getText());
            }
            int flag = controlePedido.inserePedido(codigo, quantidade);
            if (flag == -1) {
                JOptionPane.showMessageDialog(this, "Código do produto inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else if(flag == 0){
                JOptionPane.showMessageDialog(this, "Quantidade insuficiente no estoque", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Object o[] = controlePedido.getLastItem();
                campoCodigo.setText("");
                campoQuantidade.setText("");
                totalLabel.setText(controlePedido.getTotal());
                
                model.addRow(o);
            }           
        }
    }//GEN-LAST:event_incluirButtonMouseClicked

    private void campoCartaoDeCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCartaoDeCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCartaoDeCreditoActionPerformed

    private void cartaoDeCreditoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoDeCreditoButtonMouseClicked
        if (campoCartaoDeCredito.getText().isEmpty()) 
            JOptionPane.showMessageDialog(this, "Entre com o número do Cartão de Crédito", "Erro", JOptionPane.ERROR_MESSAGE);
           
        else if (campoCodigoDeSeguranca.getText().isEmpty()) 
                JOptionPane.showMessageDialog(this, "Entre com o número do código de segurança", "Erro", JOptionPane.ERROR_MESSAGE);
        else{
            String cartao = campoCartaoDeCredito.getText();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            Pagamento pagamento = new PagamentoEmCredito(controlePedido.getValorTotal(),dateFormat.format(date),cartao);
            campoCartaoDeCredito.setText("");
            campoCodigoDeSeguranca.setText("");
            creditoPanel.setVisible(false);
            controlePedido.geraVenda();
            this.geraNovoPedido();
        }
    }//GEN-LAST:event_cartaoDeCreditoButtonMouseClicked

    private void cartaoDeDebitoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoDeDebitoButtonMouseClicked
        String cartao = campoCartaoDeDebito.getText();
        if (cartao.isEmpty()) 
            JOptionPane.showMessageDialog(this, "Por favor entre com o número do cartão", "Erro", JOptionPane.ERROR_MESSAGE);
        else{
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            Pagamento pagamento = new PagamentoEmDebito(controlePedido.getValorTotal(),dateFormat.format(date),cartao);
            campoCartaoDeDebito.setText("");
            cartaoDeDebitoPanel.setVisible(false);
            controlePedido.geraVenda();
            this.geraNovoPedido();
        }
    }//GEN-LAST:event_cartaoDeDebitoButtonMouseClicked

    private void efetuarPagamentoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efetuarPagamentoButtonMouseClicked
        Pagamento pagamento;
        double total = controlePedido.getValorTotal();
        if (creditoPanel.isEnabled()) {
            campoCartaoDeCredito.setText("");
            campoCodigoDeSeguranca.setText("");
            creditoPanel.setVisible(false);
        }
        if (cartaoDeDebitoPanel.isEnabled()) {
            campoCartaoDeDebito.setText("");
            cartaoDeDebitoPanel.setVisible(false);
        }
        if (dinheiroPanel.isEnabled()) {
            campoTroco.setText("");
            dinheiroPanel.setVisible(false);
        }
        String cpf = campoCpf.getText();
        if(!cpf.isEmpty()){
            double bonus = ControleCliente.buscaCliente(cpf);
            double soma = total*0.01;
            ControleCliente.incrementaBonus(cpf, soma);
            
        }
        double valor = Double.parseDouble(campoValor.getText());
        if(total > valor){
            JOptionPane.showMessageDialog(this, "Valor inferior ao total da compra", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int opcao = pagamentosBox.getSelectedIndex();
        if (opcao == 1) {
            creditoPanel.setVisible(true);
        } else if (opcao == 2) {
            cartaoDeDebitoPanel.setVisible(true);
        } else {
            dinheiroPanel.setVisible(true);
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = new Date();
            pagamento = new PagamentoEmDinheiro(total, valor,dateFormat.format(date));
            double troco = valor - total;
            campoTroco.setText(String.format("%.2f",troco));

        }
    }//GEN-LAST:event_efetuarPagamentoButtonMouseClicked

    private void okDinheiroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okDinheiroButtonActionPerformed
            controlePedido.geraVenda();
            this.geraNovoPedido();
    }//GEN-LAST:event_okDinheiroButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            login.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void incluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirButtonActionPerformed

    }//GEN-LAST:event_incluirButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarClienteButton;
    private javax.swing.JTextField campoCartaoDeCredito;
    private javax.swing.JTextField campoCartaoDeDebito;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoCodigoDeSeguranca;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JTextField campoTroco;
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton cartaoDeCreditoButton;
    private javax.swing.JButton cartaoDeDebitoButton;
    private javax.swing.JPanel cartaoDeDebitoPanel;
    private javax.swing.JPanel creditoPanel;
    private javax.swing.JPanel dinheiroPanel;
    private javax.swing.JButton efetuarPagamentoButton;
    private javax.swing.JButton incluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton localizarClienteButton;
    private javax.swing.JButton okDinheiroButton;
    private javax.swing.JComboBox pagamentosBox;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
